# Generated by Django 3.2.2 on 2021-08-12 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210812_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='viwes',
            new_name='views',
        ),
    ]
